# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daniel Hajjar
email: daniel.hajjar16@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Student - Software Developer
baseurl: "/Portfolio" # the subpath of your site, e.g. /blog
url: "https://DanTGL.github.io" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
#twitter_username: SBootstrap
github_username:  DanTGL
#facebook_username: StartBootstrap
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://www.linkedin.com/in/daniel-hajjar

# Address information
address_city: Uppsala
address_country: Sweden

# Uncomment line below to make contact form appear instead of info
# contactform: set

# Build settings
markdown: kramdown

exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - README.md
   - LICENSE
   - feed.xml